//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viajes.DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTL_ACCESO_PERSONA
    {
        public int id_persona { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public byte tipo_usuario { get; set; }
        public byte acepta_terminos { get; set; }
        public string token_firebase { get; set; }
        public string clave_password { get; set; }
        public Nullable<System.DateTime> fecha_clave_password { get; set; }
    
        public virtual CTL_PERSONA CTL_PERSONA { get; set; }
        public virtual CTL_PERSONA CTL_PERSONA1 { get; set; }
    }
}
