//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viajes.DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTL_PRODUCTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CTL_PRODUCTO()
        {
            this.TBL_BANNERS = new HashSet<TBL_BANNERS>();
            this.M_DETALLE_PEDIDO = new HashSet<M_DETALLE_PEDIDO>();
            this.R_PERSONA_PRODUCTO_FAVORITO = new HashSet<R_PERSONA_PRODUCTO_FAVORITO>();
        }
    
        public int id_local { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public decimal precio { get; set; }
        public int id_persona_alta { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public Nullable<int> id_persona_mod { get; set; }
        public Nullable<System.DateTime> fecha_mod { get; set; }
        public string fotografia { get; set; }
        public int id_producto { get; set; }
        public byte estatus { get; set; }
    
        public virtual CTL_LOCAL CTL_LOCAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_BANNERS> TBL_BANNERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_DETALLE_PEDIDO> M_DETALLE_PEDIDO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_PERSONA_PRODUCTO_FAVORITO> R_PERSONA_PRODUCTO_FAVORITO { get; set; }
    }
}
