//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viajes.DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTL_TIPO_LOCAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CTL_TIPO_LOCAL()
        {
            this.CTL_LOCAL = new HashSet<CTL_LOCAL>();
        }
    
        public int id_tipo_local { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public byte estatus { get; set; }
        public int id_persona_alta { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public Nullable<int> id_persona_mod { get; set; }
        public Nullable<System.DateTime> fecha_mod { get; set; }
        public string fotografia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTL_LOCAL> CTL_LOCAL { get; set; }
    }
}
