//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viajes.DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTL_PERSONA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CTL_PERSONA()
        {
            this.CTL_ACCESO_PERSONA = new HashSet<CTL_ACCESO_PERSONA>();
            this.CTL_ACCESO_PERSONA1 = new HashSet<CTL_ACCESO_PERSONA>();
            this.R_PERSONA_PRODUCTO_FAVORITO = new HashSet<R_PERSONA_PRODUCTO_FAVORITO>();
            this.M_PEDIDO = new HashSet<M_PEDIDO>();
            this.M_PEDIDO1 = new HashSet<M_PEDIDO>();
            this.TBL_BANNERS = new HashSet<TBL_BANNERS>();
            this.TBL_BANNERS1 = new HashSet<TBL_BANNERS>();
            this.R_PERSONA_OPENPAY = new HashSet<R_PERSONA_OPENPAY>();
        }
    
        public int id_persona { get; set; }
        public string nombre { get; set; }
        public string sexo { get; set; }
        public short edad { get; set; }
        public string telefono { get; set; }
        public string fotografia { get; set; }
        public byte estatus { get; set; }
        public byte id_persona_alta { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public Nullable<byte> id_persona_mod { get; set; }
        public Nullable<System.DateTime> fecha_mod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTL_ACCESO_PERSONA> CTL_ACCESO_PERSONA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTL_ACCESO_PERSONA> CTL_ACCESO_PERSONA1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_PERSONA_PRODUCTO_FAVORITO> R_PERSONA_PRODUCTO_FAVORITO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_PEDIDO> M_PEDIDO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_PEDIDO> M_PEDIDO1 { get; set; }
        public virtual CTL_CONDUCTOR CTL_CONDUCTOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_BANNERS> TBL_BANNERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_BANNERS> TBL_BANNERS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_PERSONA_OPENPAY> R_PERSONA_OPENPAY { get; set; }
    }
}
