//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viajes.DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTL_LOCAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CTL_LOCAL()
        {
            this.CTL_PRODUCTO = new HashSet<CTL_PRODUCTO>();
            this.M_DETALLE_PEDIDO = new HashSet<M_DETALLE_PEDIDO>();
        }
    
        public int id_local { get; set; }
        public int id_tipo_local { get; set; }
        public string nombre { get; set; }
        public string colonia { get; set; }
        public string calle { get; set; }
        public string no_ext { get; set; }
        public string no_int { get; set; }
        public string referencias { get; set; }
        public string fotografia { get; set; }
        public Nullable<decimal> latitud { get; set; }
        public Nullable<decimal> longitud { get; set; }
        public byte estatus { get; set; }
        public int id_persona_alta { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public Nullable<int> id_persona_mod { get; set; }
        public Nullable<System.DateTime> fecha_mod { get; set; }
        public int id_costo { get; set; }
    
        public virtual CTL_COSTO CTL_COSTO { get; set; }
        public virtual CTL_TIPO_LOCAL CTL_TIPO_LOCAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTL_PRODUCTO> CTL_PRODUCTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_DETALLE_PEDIDO> M_DETALLE_PEDIDO { get; set; }
    }
}
