//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viajes.DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTL_DIRECCIONES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CTL_DIRECCIONES()
        {
            this.M_PEDIDO = new HashSet<M_PEDIDO>();
        }
    
        public int id_direccion { get; set; }
        public int id_persona { get; set; }
        public string nombre { get; set; }
        public string calle { get; set; }
        public string colonia { get; set; }
        public string no_ext { get; set; }
        public string no_int { get; set; }
        public string descripcion { get; set; }
        public decimal latitud { get; set; }
        public decimal longitud { get; set; }
        public byte estatus { get; set; }
        public int id_persona_alta { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public Nullable<int> id_persona_mod { get; set; }
        public Nullable<System.DateTime> fecha_mod { get; set; }
        public byte predeterminada { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_PEDIDO> M_PEDIDO { get; set; }
    }
}
