//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viajes.DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTL_PREGUNTA_SERVICIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CTL_PREGUNTA_SERVICIO()
        {
            this.R_PEDIDO_PREGRUNTA = new HashSet<R_PEDIDO_PREGRUNTA>();
        }
    
        public System.Guid id_pregunta { get; set; }
        public string pregunta { get; set; }
        public byte tipo_pregunta { get; set; }
        public int id_persona_alta { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public Nullable<int> id_persona_mod { get; set; }
        public Nullable<System.DateTime> fecha_mod { get; set; }
        public byte orden { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_PEDIDO_PREGRUNTA> R_PEDIDO_PREGRUNTA { get; set; }
    }
}
