//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viajes.DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_DETALLE_PEDIDO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public M_DETALLE_PEDIDO()
        {
            this.R_DETALLE_PEDIDO_EXTRAS = new HashSet<R_DETALLE_PEDIDO_EXTRAS>();
        }
    
        public int id_local { get; set; }
        public int id_producto { get; set; }
        public decimal precio { get; set; }
        public int cantidad { get; set; }
        public string observaciones { get; set; }
        public System.Guid id_detalle_pedido { get; set; }
        public System.Guid id_pedido { get; set; }
    
        public virtual CTL_LOCAL CTL_LOCAL { get; set; }
        public virtual CTL_PRODUCTO CTL_PRODUCTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_DETALLE_PEDIDO_EXTRAS> R_DETALLE_PEDIDO_EXTRAS { get; set; }
        public virtual M_PEDIDO M_PEDIDO { get; set; }
    }
}
