//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viajes.DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_DETALLE_PEDIDO
    {
        public long id_pedido { get; set; }
        public int id_local { get; set; }
        public int id_producto { get; set; }
        public decimal precio { get; set; }
        public int cantidad { get; set; }
        public string observaciones { get; set; }
        public int id_detalle_pedido { get; set; }
    
        public virtual CTL_LOCAL CTL_LOCAL { get; set; }
        public virtual CTL_PRODUCTO CTL_PRODUCTO { get; set; }
        public virtual M_PEDIDO M_PEDIDO { get; set; }
    }
}
