//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viajes.DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_DETALLE_PEDIDO_PERSONALIZADO
    {
        public System.Guid id_detalle_pedido_personalizado { get; set; }
        public System.Guid id_pedido { get; set; }
        public string nombre_local { get; set; }
        public string direccion { get; set; }
        public string referencias { get; set; }
        public string pedido { get; set; }
        public decimal latitud { get; set; }
        public decimal longitud { get; set; }
        public decimal limite_inferior { get; set; }
        public decimal limite_superior { get; set; }
        public decimal costo { get; set; }
    
        public virtual M_PEDIDO M_PEDIDO { get; set; }
    }
}
