//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viajes.DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_PEDIDO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public M_PEDIDO()
        {
            this.M_DETALLE_PEDIDO = new HashSet<M_DETALLE_PEDIDO>();
            this.M_DETALLE_PEDIDO_PERSONALIZADO = new HashSet<M_DETALLE_PEDIDO_PERSONALIZADO>();
            this.R_PEDIDO_PREGRUNTA = new HashSet<R_PEDIDO_PREGRUNTA>();
            this.TBL_COORDENADAS_CONDUCTOR = new HashSet<TBL_COORDENADAS_CONDUCTOR>();
            this.TBL_RECHAZO_PEDIDO = new HashSet<TBL_RECHAZO_PEDIDO>();
        }
    
        public int id_persona_pide { get; set; }
        public int id_direccion_entrega { get; set; }
        public Nullable<int> id_persona_entrega { get; set; }
        public Nullable<int> id_encuesta { get; set; }
        public int id_estatus { get; set; }
        public Nullable<int> calificacion { get; set; }
        public string observaciones { get; set; }
        public System.DateTime fecha_pedido { get; set; }
        public System.TimeSpan hora_pedido { get; set; }
        public Nullable<System.DateTime> fecha_entrega { get; set; }
        public Nullable<System.TimeSpan> hora_entrega { get; set; }
        public string folio { get; set; }
        public int id_metodo_pago { get; set; }
        public string referencia_pago { get; set; }
        public System.Guid id_pedido { get; set; }
        public decimal costo_envio { get; set; }
        public byte tipo_pedido { get; set; }
        public decimal propina { get; set; }
        public byte id_estatus_factura { get; set; }
        public decimal iva { get; set; }
        public int tiempo_espera { get; set; }
    
        public virtual CTL_DIRECCIONES CTL_DIRECCIONES { get; set; }
        public virtual CTL_ESTATUS_PEDIDO CTL_ESTATUS_PEDIDO { get; set; }
        public virtual CTL_METODO_PAGO CTL_METODO_PAGO { get; set; }
        public virtual CTL_PERSONA CTL_PERSONA { get; set; }
        public virtual CTL_PERSONA CTL_PERSONA1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_DETALLE_PEDIDO> M_DETALLE_PEDIDO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_DETALLE_PEDIDO_PERSONALIZADO> M_DETALLE_PEDIDO_PERSONALIZADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_PEDIDO_PREGRUNTA> R_PEDIDO_PREGRUNTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_COORDENADAS_CONDUCTOR> TBL_COORDENADAS_CONDUCTOR { get; set; }
        public virtual CTL_ESTATUS_FACTURA CTL_ESTATUS_FACTURA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_RECHAZO_PEDIDO> TBL_RECHAZO_PEDIDO { get; set; }
    }
}
