//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viajes.DAL.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ViajesEntities : DbContext
    {
        public ViajesEntities()
            : base("name=ViajesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CTL_ACCESO_PERSONA> CTL_ACCESO_PERSONA { get; set; }
        public virtual DbSet<CTL_CONDUCTOR> CTL_CONDUCTOR { get; set; }
        public virtual DbSet<CTL_COSTO> CTL_COSTO { get; set; }
        public virtual DbSet<CTL_DIRECCIONES> CTL_DIRECCIONES { get; set; }
        public virtual DbSet<CTL_ESTATUS_PEDIDO> CTL_ESTATUS_PEDIDO { get; set; }
        public virtual DbSet<CTL_EXTRAS_PRODUCTO> CTL_EXTRAS_PRODUCTO { get; set; }
        public virtual DbSet<CTL_LOCAL> CTL_LOCAL { get; set; }
        public virtual DbSet<CTL_METODO_PAGO> CTL_METODO_PAGO { get; set; }
        public virtual DbSet<CTL_PERSONA> CTL_PERSONA { get; set; }
        public virtual DbSet<CTL_PREGUNTA_SERVICIO> CTL_PREGUNTA_SERVICIO { get; set; }
        public virtual DbSet<CTL_PRODUCTO> CTL_PRODUCTO { get; set; }
        public virtual DbSet<CTL_TIPO_LOCAL> CTL_TIPO_LOCAL { get; set; }
        public virtual DbSet<M_DETALLE_PEDIDO> M_DETALLE_PEDIDO { get; set; }
        public virtual DbSet<M_DETALLE_PEDIDO_PERSONALIZADO> M_DETALLE_PEDIDO_PERSONALIZADO { get; set; }
        public virtual DbSet<M_PEDIDO> M_PEDIDO { get; set; }
        public virtual DbSet<R_DETALLE_PEDIDO_EXTRAS> R_DETALLE_PEDIDO_EXTRAS { get; set; }
        public virtual DbSet<R_PEDIDO_PREGRUNTA> R_PEDIDO_PREGRUNTA { get; set; }
        public virtual DbSet<R_PERSONA_OPENPAY> R_PERSONA_OPENPAY { get; set; }
        public virtual DbSet<R_PERSONA_PRODUCTO_FAVORITO> R_PERSONA_PRODUCTO_FAVORITO { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TBL_BANNERS> TBL_BANNERS { get; set; }
        public virtual DbSet<TBL_COORDENADAS_CONDUCTOR> TBL_COORDENADAS_CONDUCTOR { get; set; }
        public virtual DbSet<TBL_QR_TIENDA> TBL_QR_TIENDA { get; set; }
        public virtual DbSet<TBL_TARIFA_ENVIO> TBL_TARIFA_ENVIO { get; set; }
        public virtual DbSet<CTL_ESTATUS_FACTURA> CTL_ESTATUS_FACTURA { get; set; }
        public virtual DbSet<TBL_RECHAZO_PEDIDO> TBL_RECHAZO_PEDIDO { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int SP_DIRECCION(Nullable<int> pIN_ID_DIRECCION, string pIN_NOMBRE, string pIN_CALLE, string pIN_COLONIA, string pIN_DESCRIPCION, string pIN_NO_EXT, string pIN_NO_INT, Nullable<decimal> pIN_LATITUD, Nullable<decimal> pIN_LONGITUD, Nullable<int> pIN_ID_PERSONA, Nullable<int> pIN_ID_PERSONA_MOVIMIENTO, Nullable<byte> pIN_ESTATUS, Nullable<byte> pIN_PREDETERMINADA, string pIN_TIPO_MOVIMIENTO, ObjectParameter rET_NUMEROERROR, ObjectParameter rET_MENSAJEERROR, ObjectParameter rET_VALORDEVUELTO)
        {
            var pIN_ID_DIRECCIONParameter = pIN_ID_DIRECCION.HasValue ?
                new ObjectParameter("PIN_ID_DIRECCION", pIN_ID_DIRECCION) :
                new ObjectParameter("PIN_ID_DIRECCION", typeof(int));
    
            var pIN_NOMBREParameter = pIN_NOMBRE != null ?
                new ObjectParameter("PIN_NOMBRE", pIN_NOMBRE) :
                new ObjectParameter("PIN_NOMBRE", typeof(string));
    
            var pIN_CALLEParameter = pIN_CALLE != null ?
                new ObjectParameter("PIN_CALLE", pIN_CALLE) :
                new ObjectParameter("PIN_CALLE", typeof(string));
    
            var pIN_COLONIAParameter = pIN_COLONIA != null ?
                new ObjectParameter("PIN_COLONIA", pIN_COLONIA) :
                new ObjectParameter("PIN_COLONIA", typeof(string));
    
            var pIN_DESCRIPCIONParameter = pIN_DESCRIPCION != null ?
                new ObjectParameter("PIN_DESCRIPCION", pIN_DESCRIPCION) :
                new ObjectParameter("PIN_DESCRIPCION", typeof(string));
    
            var pIN_NO_EXTParameter = pIN_NO_EXT != null ?
                new ObjectParameter("PIN_NO_EXT", pIN_NO_EXT) :
                new ObjectParameter("PIN_NO_EXT", typeof(string));
    
            var pIN_NO_INTParameter = pIN_NO_INT != null ?
                new ObjectParameter("PIN_NO_INT", pIN_NO_INT) :
                new ObjectParameter("PIN_NO_INT", typeof(string));
    
            var pIN_LATITUDParameter = pIN_LATITUD.HasValue ?
                new ObjectParameter("PIN_LATITUD", pIN_LATITUD) :
                new ObjectParameter("PIN_LATITUD", typeof(decimal));
    
            var pIN_LONGITUDParameter = pIN_LONGITUD.HasValue ?
                new ObjectParameter("PIN_LONGITUD", pIN_LONGITUD) :
                new ObjectParameter("PIN_LONGITUD", typeof(decimal));
    
            var pIN_ID_PERSONAParameter = pIN_ID_PERSONA.HasValue ?
                new ObjectParameter("PIN_ID_PERSONA", pIN_ID_PERSONA) :
                new ObjectParameter("PIN_ID_PERSONA", typeof(int));
    
            var pIN_ID_PERSONA_MOVIMIENTOParameter = pIN_ID_PERSONA_MOVIMIENTO.HasValue ?
                new ObjectParameter("PIN_ID_PERSONA_MOVIMIENTO", pIN_ID_PERSONA_MOVIMIENTO) :
                new ObjectParameter("PIN_ID_PERSONA_MOVIMIENTO", typeof(int));
    
            var pIN_ESTATUSParameter = pIN_ESTATUS.HasValue ?
                new ObjectParameter("PIN_ESTATUS", pIN_ESTATUS) :
                new ObjectParameter("PIN_ESTATUS", typeof(byte));
    
            var pIN_PREDETERMINADAParameter = pIN_PREDETERMINADA.HasValue ?
                new ObjectParameter("PIN_PREDETERMINADA", pIN_PREDETERMINADA) :
                new ObjectParameter("PIN_PREDETERMINADA", typeof(byte));
    
            var pIN_TIPO_MOVIMIENTOParameter = pIN_TIPO_MOVIMIENTO != null ?
                new ObjectParameter("PIN_TIPO_MOVIMIENTO", pIN_TIPO_MOVIMIENTO) :
                new ObjectParameter("PIN_TIPO_MOVIMIENTO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DIRECCION", pIN_ID_DIRECCIONParameter, pIN_NOMBREParameter, pIN_CALLEParameter, pIN_COLONIAParameter, pIN_DESCRIPCIONParameter, pIN_NO_EXTParameter, pIN_NO_INTParameter, pIN_LATITUDParameter, pIN_LONGITUDParameter, pIN_ID_PERSONAParameter, pIN_ID_PERSONA_MOVIMIENTOParameter, pIN_ESTATUSParameter, pIN_PREDETERMINADAParameter, pIN_TIPO_MOVIMIENTOParameter, rET_NUMEROERROR, rET_MENSAJEERROR, rET_VALORDEVUELTO);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int SP_LOCAL(Nullable<int> pIN_ID_LOCAL, string pIN_NOMBRE, string pIN_REFERENCIAS, Nullable<decimal> pIN_LATITUD, Nullable<decimal> pIN_LONGITUD, string pIN_FOTOGRAFIA, string pIN_CALLE, string pIN_COLONIA, string pIN_NO_EXT, string pIN_NO_INT, Nullable<int> pIN_ID_COSTO, Nullable<int> pIN_ID_TIPO_LOCAL, Nullable<int> pIN_ID_PERSONA_MOVIMIENTO, Nullable<int> pIN_ID_PERSONA_RESPONSABLE, Nullable<byte> pIN_ESTATUS, string pIN_TIPO_MOVIMIENTO, ObjectParameter rET_NUMEROERROR, ObjectParameter rET_MENSAJEERROR, ObjectParameter rET_VALORDEVUELTO)
        {
            var pIN_ID_LOCALParameter = pIN_ID_LOCAL.HasValue ?
                new ObjectParameter("PIN_ID_LOCAL", pIN_ID_LOCAL) :
                new ObjectParameter("PIN_ID_LOCAL", typeof(int));
    
            var pIN_NOMBREParameter = pIN_NOMBRE != null ?
                new ObjectParameter("PIN_NOMBRE", pIN_NOMBRE) :
                new ObjectParameter("PIN_NOMBRE", typeof(string));
    
            var pIN_REFERENCIASParameter = pIN_REFERENCIAS != null ?
                new ObjectParameter("PIN_REFERENCIAS", pIN_REFERENCIAS) :
                new ObjectParameter("PIN_REFERENCIAS", typeof(string));
    
            var pIN_LATITUDParameter = pIN_LATITUD.HasValue ?
                new ObjectParameter("PIN_LATITUD", pIN_LATITUD) :
                new ObjectParameter("PIN_LATITUD", typeof(decimal));
    
            var pIN_LONGITUDParameter = pIN_LONGITUD.HasValue ?
                new ObjectParameter("PIN_LONGITUD", pIN_LONGITUD) :
                new ObjectParameter("PIN_LONGITUD", typeof(decimal));
    
            var pIN_FOTOGRAFIAParameter = pIN_FOTOGRAFIA != null ?
                new ObjectParameter("PIN_FOTOGRAFIA", pIN_FOTOGRAFIA) :
                new ObjectParameter("PIN_FOTOGRAFIA", typeof(string));
    
            var pIN_CALLEParameter = pIN_CALLE != null ?
                new ObjectParameter("PIN_CALLE", pIN_CALLE) :
                new ObjectParameter("PIN_CALLE", typeof(string));
    
            var pIN_COLONIAParameter = pIN_COLONIA != null ?
                new ObjectParameter("PIN_COLONIA", pIN_COLONIA) :
                new ObjectParameter("PIN_COLONIA", typeof(string));
    
            var pIN_NO_EXTParameter = pIN_NO_EXT != null ?
                new ObjectParameter("PIN_NO_EXT", pIN_NO_EXT) :
                new ObjectParameter("PIN_NO_EXT", typeof(string));
    
            var pIN_NO_INTParameter = pIN_NO_INT != null ?
                new ObjectParameter("PIN_NO_INT", pIN_NO_INT) :
                new ObjectParameter("PIN_NO_INT", typeof(string));
    
            var pIN_ID_COSTOParameter = pIN_ID_COSTO.HasValue ?
                new ObjectParameter("PIN_ID_COSTO", pIN_ID_COSTO) :
                new ObjectParameter("PIN_ID_COSTO", typeof(int));
    
            var pIN_ID_TIPO_LOCALParameter = pIN_ID_TIPO_LOCAL.HasValue ?
                new ObjectParameter("PIN_ID_TIPO_LOCAL", pIN_ID_TIPO_LOCAL) :
                new ObjectParameter("PIN_ID_TIPO_LOCAL", typeof(int));
    
            var pIN_ID_PERSONA_MOVIMIENTOParameter = pIN_ID_PERSONA_MOVIMIENTO.HasValue ?
                new ObjectParameter("PIN_ID_PERSONA_MOVIMIENTO", pIN_ID_PERSONA_MOVIMIENTO) :
                new ObjectParameter("PIN_ID_PERSONA_MOVIMIENTO", typeof(int));
    
            var pIN_ID_PERSONA_RESPONSABLEParameter = pIN_ID_PERSONA_RESPONSABLE.HasValue ?
                new ObjectParameter("PIN_ID_PERSONA_RESPONSABLE", pIN_ID_PERSONA_RESPONSABLE) :
                new ObjectParameter("PIN_ID_PERSONA_RESPONSABLE", typeof(int));
    
            var pIN_ESTATUSParameter = pIN_ESTATUS.HasValue ?
                new ObjectParameter("PIN_ESTATUS", pIN_ESTATUS) :
                new ObjectParameter("PIN_ESTATUS", typeof(byte));
    
            var pIN_TIPO_MOVIMIENTOParameter = pIN_TIPO_MOVIMIENTO != null ?
                new ObjectParameter("PIN_TIPO_MOVIMIENTO", pIN_TIPO_MOVIMIENTO) :
                new ObjectParameter("PIN_TIPO_MOVIMIENTO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_LOCAL", pIN_ID_LOCALParameter, pIN_NOMBREParameter, pIN_REFERENCIASParameter, pIN_LATITUDParameter, pIN_LONGITUDParameter, pIN_FOTOGRAFIAParameter, pIN_CALLEParameter, pIN_COLONIAParameter, pIN_NO_EXTParameter, pIN_NO_INTParameter, pIN_ID_COSTOParameter, pIN_ID_TIPO_LOCALParameter, pIN_ID_PERSONA_MOVIMIENTOParameter, pIN_ID_PERSONA_RESPONSABLEParameter, pIN_ESTATUSParameter, pIN_TIPO_MOVIMIENTOParameter, rET_NUMEROERROR, rET_MENSAJEERROR, rET_VALORDEVUELTO);
        }
    
        public virtual int SP_LOGIN(string pIN_EMAIL, string pIN_PASSWORD, Nullable<byte> pIN_TIPO_USUARIO, ObjectParameter rET_ID_PERSONA, ObjectParameter rET_NUMEROERROR, ObjectParameter rET_MENSAJEERROR, ObjectParameter rET_VALORDEVUELTO)
        {
            var pIN_EMAILParameter = pIN_EMAIL != null ?
                new ObjectParameter("PIN_EMAIL", pIN_EMAIL) :
                new ObjectParameter("PIN_EMAIL", typeof(string));
    
            var pIN_PASSWORDParameter = pIN_PASSWORD != null ?
                new ObjectParameter("PIN_PASSWORD", pIN_PASSWORD) :
                new ObjectParameter("PIN_PASSWORD", typeof(string));
    
            var pIN_TIPO_USUARIOParameter = pIN_TIPO_USUARIO.HasValue ?
                new ObjectParameter("PIN_TIPO_USUARIO", pIN_TIPO_USUARIO) :
                new ObjectParameter("PIN_TIPO_USUARIO", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_LOGIN", pIN_EMAILParameter, pIN_PASSWORDParameter, pIN_TIPO_USUARIOParameter, rET_ID_PERSONA, rET_NUMEROERROR, rET_MENSAJEERROR, rET_VALORDEVUELTO);
        }
    
        public virtual int SP_PEDIDO(Nullable<System.Guid> pIN_ID_PEDIDO, Nullable<int> pIN_ID_PERSONA_PIDE, Nullable<int> pIN_ID_DIRECCION_ENTREGA, Nullable<int> pIN_ID_PERSONA_ENTREGA, string pIN_OBSERVACIONES, string pIN_FOLIO, Nullable<int> pIN_ID_METODO_PAGO, Nullable<int> pIN_ID_ESTATUS, string pIN_DETALLE, string pIN_TIPO_MOVIMIENTO, string pIN_REFERENCIA_PAGO, Nullable<decimal> pIN_COSTO_ENVIO, Nullable<byte> pIN_TIPO_PEDIDO, Nullable<decimal> pIN_PROPINA, Nullable<byte> pIN_ID_ESTATUS_FACTURA, Nullable<decimal> pIN_IVA, ObjectParameter rET_NUMEROERROR, ObjectParameter rET_MENSAJEERROR, ObjectParameter rET_VALORDEVUELTO)
        {
            var pIN_ID_PEDIDOParameter = pIN_ID_PEDIDO.HasValue ?
                new ObjectParameter("PIN_ID_PEDIDO", pIN_ID_PEDIDO) :
                new ObjectParameter("PIN_ID_PEDIDO", typeof(System.Guid));
    
            var pIN_ID_PERSONA_PIDEParameter = pIN_ID_PERSONA_PIDE.HasValue ?
                new ObjectParameter("PIN_ID_PERSONA_PIDE", pIN_ID_PERSONA_PIDE) :
                new ObjectParameter("PIN_ID_PERSONA_PIDE", typeof(int));
    
            var pIN_ID_DIRECCION_ENTREGAParameter = pIN_ID_DIRECCION_ENTREGA.HasValue ?
                new ObjectParameter("PIN_ID_DIRECCION_ENTREGA", pIN_ID_DIRECCION_ENTREGA) :
                new ObjectParameter("PIN_ID_DIRECCION_ENTREGA", typeof(int));
    
            var pIN_ID_PERSONA_ENTREGAParameter = pIN_ID_PERSONA_ENTREGA.HasValue ?
                new ObjectParameter("PIN_ID_PERSONA_ENTREGA", pIN_ID_PERSONA_ENTREGA) :
                new ObjectParameter("PIN_ID_PERSONA_ENTREGA", typeof(int));
    
            var pIN_OBSERVACIONESParameter = pIN_OBSERVACIONES != null ?
                new ObjectParameter("PIN_OBSERVACIONES", pIN_OBSERVACIONES) :
                new ObjectParameter("PIN_OBSERVACIONES", typeof(string));
    
            var pIN_FOLIOParameter = pIN_FOLIO != null ?
                new ObjectParameter("PIN_FOLIO", pIN_FOLIO) :
                new ObjectParameter("PIN_FOLIO", typeof(string));
    
            var pIN_ID_METODO_PAGOParameter = pIN_ID_METODO_PAGO.HasValue ?
                new ObjectParameter("PIN_ID_METODO_PAGO", pIN_ID_METODO_PAGO) :
                new ObjectParameter("PIN_ID_METODO_PAGO", typeof(int));
    
            var pIN_ID_ESTATUSParameter = pIN_ID_ESTATUS.HasValue ?
                new ObjectParameter("PIN_ID_ESTATUS", pIN_ID_ESTATUS) :
                new ObjectParameter("PIN_ID_ESTATUS", typeof(int));
    
            var pIN_DETALLEParameter = pIN_DETALLE != null ?
                new ObjectParameter("PIN_DETALLE", pIN_DETALLE) :
                new ObjectParameter("PIN_DETALLE", typeof(string));
    
            var pIN_TIPO_MOVIMIENTOParameter = pIN_TIPO_MOVIMIENTO != null ?
                new ObjectParameter("PIN_TIPO_MOVIMIENTO", pIN_TIPO_MOVIMIENTO) :
                new ObjectParameter("PIN_TIPO_MOVIMIENTO", typeof(string));
    
            var pIN_REFERENCIA_PAGOParameter = pIN_REFERENCIA_PAGO != null ?
                new ObjectParameter("PIN_REFERENCIA_PAGO", pIN_REFERENCIA_PAGO) :
                new ObjectParameter("PIN_REFERENCIA_PAGO", typeof(string));
    
            var pIN_COSTO_ENVIOParameter = pIN_COSTO_ENVIO.HasValue ?
                new ObjectParameter("PIN_COSTO_ENVIO", pIN_COSTO_ENVIO) :
                new ObjectParameter("PIN_COSTO_ENVIO", typeof(decimal));
    
            var pIN_TIPO_PEDIDOParameter = pIN_TIPO_PEDIDO.HasValue ?
                new ObjectParameter("PIN_TIPO_PEDIDO", pIN_TIPO_PEDIDO) :
                new ObjectParameter("PIN_TIPO_PEDIDO", typeof(byte));
    
            var pIN_PROPINAParameter = pIN_PROPINA.HasValue ?
                new ObjectParameter("PIN_PROPINA", pIN_PROPINA) :
                new ObjectParameter("PIN_PROPINA", typeof(decimal));
    
            var pIN_ID_ESTATUS_FACTURAParameter = pIN_ID_ESTATUS_FACTURA.HasValue ?
                new ObjectParameter("PIN_ID_ESTATUS_FACTURA", pIN_ID_ESTATUS_FACTURA) :
                new ObjectParameter("PIN_ID_ESTATUS_FACTURA", typeof(byte));
    
            var pIN_IVAParameter = pIN_IVA.HasValue ?
                new ObjectParameter("PIN_IVA", pIN_IVA) :
                new ObjectParameter("PIN_IVA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PEDIDO", pIN_ID_PEDIDOParameter, pIN_ID_PERSONA_PIDEParameter, pIN_ID_DIRECCION_ENTREGAParameter, pIN_ID_PERSONA_ENTREGAParameter, pIN_OBSERVACIONESParameter, pIN_FOLIOParameter, pIN_ID_METODO_PAGOParameter, pIN_ID_ESTATUSParameter, pIN_DETALLEParameter, pIN_TIPO_MOVIMIENTOParameter, pIN_REFERENCIA_PAGOParameter, pIN_COSTO_ENVIOParameter, pIN_TIPO_PEDIDOParameter, pIN_PROPINAParameter, pIN_ID_ESTATUS_FACTURAParameter, pIN_IVAParameter, rET_NUMEROERROR, rET_MENSAJEERROR, rET_VALORDEVUELTO);
        }
    
        public virtual int SP_PERSONA(Nullable<int> pIN_ID_PERSONA, string pIN_NOMBRE, string pIN_TELEFONO, string pIN_FOTOGRAFIA, string pIN_EMAIL, string pIN_PASSWORD, Nullable<byte> pIN_TIPO_USUARIO, string pIN_TOKEN_FIREBASE, string pIN_SEXO, string pIN_COLONIA, string pIN_CALLLE, string pIN_NO_EXT, string pIN_NO_INT, string pIN_NO_LICENCIA, string pIN_NO_PLACAS, Nullable<byte> pIN_ID_TIPO_CONDUCTOR, string pIN_CLAVE_PASSWORD, string pIN_TIPO_MOVIMIENTO, Nullable<int> pIN_ID_PERSONA_MOD, ObjectParameter rET_ID_PERSONA, ObjectParameter rET_NUMEROERROR, ObjectParameter rET_MENSAJEERROR, ObjectParameter rET_VALORDEVUELTO)
        {
            var pIN_ID_PERSONAParameter = pIN_ID_PERSONA.HasValue ?
                new ObjectParameter("PIN_ID_PERSONA", pIN_ID_PERSONA) :
                new ObjectParameter("PIN_ID_PERSONA", typeof(int));
    
            var pIN_NOMBREParameter = pIN_NOMBRE != null ?
                new ObjectParameter("PIN_NOMBRE", pIN_NOMBRE) :
                new ObjectParameter("PIN_NOMBRE", typeof(string));
    
            var pIN_TELEFONOParameter = pIN_TELEFONO != null ?
                new ObjectParameter("PIN_TELEFONO", pIN_TELEFONO) :
                new ObjectParameter("PIN_TELEFONO", typeof(string));
    
            var pIN_FOTOGRAFIAParameter = pIN_FOTOGRAFIA != null ?
                new ObjectParameter("PIN_FOTOGRAFIA", pIN_FOTOGRAFIA) :
                new ObjectParameter("PIN_FOTOGRAFIA", typeof(string));
    
            var pIN_EMAILParameter = pIN_EMAIL != null ?
                new ObjectParameter("PIN_EMAIL", pIN_EMAIL) :
                new ObjectParameter("PIN_EMAIL", typeof(string));
    
            var pIN_PASSWORDParameter = pIN_PASSWORD != null ?
                new ObjectParameter("PIN_PASSWORD", pIN_PASSWORD) :
                new ObjectParameter("PIN_PASSWORD", typeof(string));
    
            var pIN_TIPO_USUARIOParameter = pIN_TIPO_USUARIO.HasValue ?
                new ObjectParameter("PIN_TIPO_USUARIO", pIN_TIPO_USUARIO) :
                new ObjectParameter("PIN_TIPO_USUARIO", typeof(byte));
    
            var pIN_TOKEN_FIREBASEParameter = pIN_TOKEN_FIREBASE != null ?
                new ObjectParameter("PIN_TOKEN_FIREBASE", pIN_TOKEN_FIREBASE) :
                new ObjectParameter("PIN_TOKEN_FIREBASE", typeof(string));
    
            var pIN_SEXOParameter = pIN_SEXO != null ?
                new ObjectParameter("PIN_SEXO", pIN_SEXO) :
                new ObjectParameter("PIN_SEXO", typeof(string));
    
            var pIN_COLONIAParameter = pIN_COLONIA != null ?
                new ObjectParameter("PIN_COLONIA", pIN_COLONIA) :
                new ObjectParameter("PIN_COLONIA", typeof(string));
    
            var pIN_CALLLEParameter = pIN_CALLLE != null ?
                new ObjectParameter("PIN_CALLLE", pIN_CALLLE) :
                new ObjectParameter("PIN_CALLLE", typeof(string));
    
            var pIN_NO_EXTParameter = pIN_NO_EXT != null ?
                new ObjectParameter("PIN_NO_EXT", pIN_NO_EXT) :
                new ObjectParameter("PIN_NO_EXT", typeof(string));
    
            var pIN_NO_INTParameter = pIN_NO_INT != null ?
                new ObjectParameter("PIN_NO_INT", pIN_NO_INT) :
                new ObjectParameter("PIN_NO_INT", typeof(string));
    
            var pIN_NO_LICENCIAParameter = pIN_NO_LICENCIA != null ?
                new ObjectParameter("PIN_NO_LICENCIA", pIN_NO_LICENCIA) :
                new ObjectParameter("PIN_NO_LICENCIA", typeof(string));
    
            var pIN_NO_PLACASParameter = pIN_NO_PLACAS != null ?
                new ObjectParameter("PIN_NO_PLACAS", pIN_NO_PLACAS) :
                new ObjectParameter("PIN_NO_PLACAS", typeof(string));
    
            var pIN_ID_TIPO_CONDUCTORParameter = pIN_ID_TIPO_CONDUCTOR.HasValue ?
                new ObjectParameter("PIN_ID_TIPO_CONDUCTOR", pIN_ID_TIPO_CONDUCTOR) :
                new ObjectParameter("PIN_ID_TIPO_CONDUCTOR", typeof(byte));
    
            var pIN_CLAVE_PASSWORDParameter = pIN_CLAVE_PASSWORD != null ?
                new ObjectParameter("PIN_CLAVE_PASSWORD", pIN_CLAVE_PASSWORD) :
                new ObjectParameter("PIN_CLAVE_PASSWORD", typeof(string));
    
            var pIN_TIPO_MOVIMIENTOParameter = pIN_TIPO_MOVIMIENTO != null ?
                new ObjectParameter("PIN_TIPO_MOVIMIENTO", pIN_TIPO_MOVIMIENTO) :
                new ObjectParameter("PIN_TIPO_MOVIMIENTO", typeof(string));
    
            var pIN_ID_PERSONA_MODParameter = pIN_ID_PERSONA_MOD.HasValue ?
                new ObjectParameter("PIN_ID_PERSONA_MOD", pIN_ID_PERSONA_MOD) :
                new ObjectParameter("PIN_ID_PERSONA_MOD", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PERSONA", pIN_ID_PERSONAParameter, pIN_NOMBREParameter, pIN_TELEFONOParameter, pIN_FOTOGRAFIAParameter, pIN_EMAILParameter, pIN_PASSWORDParameter, pIN_TIPO_USUARIOParameter, pIN_TOKEN_FIREBASEParameter, pIN_SEXOParameter, pIN_COLONIAParameter, pIN_CALLLEParameter, pIN_NO_EXTParameter, pIN_NO_INTParameter, pIN_NO_LICENCIAParameter, pIN_NO_PLACASParameter, pIN_ID_TIPO_CONDUCTORParameter, pIN_CLAVE_PASSWORDParameter, pIN_TIPO_MOVIMIENTOParameter, pIN_ID_PERSONA_MODParameter, rET_ID_PERSONA, rET_NUMEROERROR, rET_MENSAJEERROR, rET_VALORDEVUELTO);
        }
    
        public virtual int SP_PRODUCTO(Nullable<int> pIN_ID_PRODUCTO, string pIN_NOMBRE, string pIN_DESCRIPCION, Nullable<decimal> pIN_PRECIO, string pIN_FOTOGRAFIA, Nullable<int> pIN_ID_LOCAL, Nullable<int> pIN_ID_PERSONA_MOVIMIENTO, Nullable<byte> pIN_ESTATUS, string pIN_TIPO_MOVIMIENTO, ObjectParameter rET_NUMEROERROR, ObjectParameter rET_MENSAJEERROR, ObjectParameter rET_VALORDEVUELTO)
        {
            var pIN_ID_PRODUCTOParameter = pIN_ID_PRODUCTO.HasValue ?
                new ObjectParameter("PIN_ID_PRODUCTO", pIN_ID_PRODUCTO) :
                new ObjectParameter("PIN_ID_PRODUCTO", typeof(int));
    
            var pIN_NOMBREParameter = pIN_NOMBRE != null ?
                new ObjectParameter("PIN_NOMBRE", pIN_NOMBRE) :
                new ObjectParameter("PIN_NOMBRE", typeof(string));
    
            var pIN_DESCRIPCIONParameter = pIN_DESCRIPCION != null ?
                new ObjectParameter("PIN_DESCRIPCION", pIN_DESCRIPCION) :
                new ObjectParameter("PIN_DESCRIPCION", typeof(string));
    
            var pIN_PRECIOParameter = pIN_PRECIO.HasValue ?
                new ObjectParameter("PIN_PRECIO", pIN_PRECIO) :
                new ObjectParameter("PIN_PRECIO", typeof(decimal));
    
            var pIN_FOTOGRAFIAParameter = pIN_FOTOGRAFIA != null ?
                new ObjectParameter("PIN_FOTOGRAFIA", pIN_FOTOGRAFIA) :
                new ObjectParameter("PIN_FOTOGRAFIA", typeof(string));
    
            var pIN_ID_LOCALParameter = pIN_ID_LOCAL.HasValue ?
                new ObjectParameter("PIN_ID_LOCAL", pIN_ID_LOCAL) :
                new ObjectParameter("PIN_ID_LOCAL", typeof(int));
    
            var pIN_ID_PERSONA_MOVIMIENTOParameter = pIN_ID_PERSONA_MOVIMIENTO.HasValue ?
                new ObjectParameter("PIN_ID_PERSONA_MOVIMIENTO", pIN_ID_PERSONA_MOVIMIENTO) :
                new ObjectParameter("PIN_ID_PERSONA_MOVIMIENTO", typeof(int));
    
            var pIN_ESTATUSParameter = pIN_ESTATUS.HasValue ?
                new ObjectParameter("PIN_ESTATUS", pIN_ESTATUS) :
                new ObjectParameter("PIN_ESTATUS", typeof(byte));
    
            var pIN_TIPO_MOVIMIENTOParameter = pIN_TIPO_MOVIMIENTO != null ?
                new ObjectParameter("PIN_TIPO_MOVIMIENTO", pIN_TIPO_MOVIMIENTO) :
                new ObjectParameter("PIN_TIPO_MOVIMIENTO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PRODUCTO", pIN_ID_PRODUCTOParameter, pIN_NOMBREParameter, pIN_DESCRIPCIONParameter, pIN_PRECIOParameter, pIN_FOTOGRAFIAParameter, pIN_ID_LOCALParameter, pIN_ID_PERSONA_MOVIMIENTOParameter, pIN_ESTATUSParameter, pIN_TIPO_MOVIMIENTOParameter, rET_NUMEROERROR, rET_MENSAJEERROR, rET_VALORDEVUELTO);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int SP_ACTUALIZA_PASSWORD(Nullable<int> pIN_ID_PERSONA, string pIN_PASSWORD, Nullable<int> pIN_TIPO_USUARIO, string pIN_TOKEN_PASSWORD, ObjectParameter rET_NUMEROERROR, ObjectParameter rET_MENSAJEERROR, ObjectParameter rET_VALORDEVUELTO)
        {
            var pIN_ID_PERSONAParameter = pIN_ID_PERSONA.HasValue ?
                new ObjectParameter("PIN_ID_PERSONA", pIN_ID_PERSONA) :
                new ObjectParameter("PIN_ID_PERSONA", typeof(int));
    
            var pIN_PASSWORDParameter = pIN_PASSWORD != null ?
                new ObjectParameter("PIN_PASSWORD", pIN_PASSWORD) :
                new ObjectParameter("PIN_PASSWORD", typeof(string));
    
            var pIN_TIPO_USUARIOParameter = pIN_TIPO_USUARIO.HasValue ?
                new ObjectParameter("PIN_TIPO_USUARIO", pIN_TIPO_USUARIO) :
                new ObjectParameter("PIN_TIPO_USUARIO", typeof(int));
    
            var pIN_TOKEN_PASSWORDParameter = pIN_TOKEN_PASSWORD != null ?
                new ObjectParameter("PIN_TOKEN_PASSWORD", pIN_TOKEN_PASSWORD) :
                new ObjectParameter("PIN_TOKEN_PASSWORD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ACTUALIZA_PASSWORD", pIN_ID_PERSONAParameter, pIN_PASSWORDParameter, pIN_TIPO_USUARIOParameter, pIN_TOKEN_PASSWORDParameter, rET_NUMEROERROR, rET_MENSAJEERROR, rET_VALORDEVUELTO);
        }
    
        public virtual int SP_BANNER(Nullable<System.Guid> pIN_ID_BANNER, string pIN_NOMBRE, Nullable<int> pIN_ID_PRODUCTO, string pIN_FOTOGRAFIA, Nullable<int> pIN_ID_PERSONA_MOVIMIENTO, Nullable<byte> pIN_ESTATUS, string pIN_TIPO_MOVIMIENTO, ObjectParameter rET_NUMEROERROR, ObjectParameter rET_MENSAJEERROR, ObjectParameter rET_VALORDEVUELTO)
        {
            var pIN_ID_BANNERParameter = pIN_ID_BANNER.HasValue ?
                new ObjectParameter("PIN_ID_BANNER", pIN_ID_BANNER) :
                new ObjectParameter("PIN_ID_BANNER", typeof(System.Guid));
    
            var pIN_NOMBREParameter = pIN_NOMBRE != null ?
                new ObjectParameter("PIN_NOMBRE", pIN_NOMBRE) :
                new ObjectParameter("PIN_NOMBRE", typeof(string));
    
            var pIN_ID_PRODUCTOParameter = pIN_ID_PRODUCTO.HasValue ?
                new ObjectParameter("PIN_ID_PRODUCTO", pIN_ID_PRODUCTO) :
                new ObjectParameter("PIN_ID_PRODUCTO", typeof(int));
    
            var pIN_FOTOGRAFIAParameter = pIN_FOTOGRAFIA != null ?
                new ObjectParameter("PIN_FOTOGRAFIA", pIN_FOTOGRAFIA) :
                new ObjectParameter("PIN_FOTOGRAFIA", typeof(string));
    
            var pIN_ID_PERSONA_MOVIMIENTOParameter = pIN_ID_PERSONA_MOVIMIENTO.HasValue ?
                new ObjectParameter("PIN_ID_PERSONA_MOVIMIENTO", pIN_ID_PERSONA_MOVIMIENTO) :
                new ObjectParameter("PIN_ID_PERSONA_MOVIMIENTO", typeof(int));
    
            var pIN_ESTATUSParameter = pIN_ESTATUS.HasValue ?
                new ObjectParameter("PIN_ESTATUS", pIN_ESTATUS) :
                new ObjectParameter("PIN_ESTATUS", typeof(byte));
    
            var pIN_TIPO_MOVIMIENTOParameter = pIN_TIPO_MOVIMIENTO != null ?
                new ObjectParameter("PIN_TIPO_MOVIMIENTO", pIN_TIPO_MOVIMIENTO) :
                new ObjectParameter("PIN_TIPO_MOVIMIENTO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_BANNER", pIN_ID_BANNERParameter, pIN_NOMBREParameter, pIN_ID_PRODUCTOParameter, pIN_FOTOGRAFIAParameter, pIN_ID_PERSONA_MOVIMIENTOParameter, pIN_ESTATUSParameter, pIN_TIPO_MOVIMIENTOParameter, rET_NUMEROERROR, rET_MENSAJEERROR, rET_VALORDEVUELTO);
        }
    }
}
