//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viajes.DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_DETALLE_PEDIDO_EXTRAS
    {
        public System.Guid id_detalle_pedido { get; set; }
        public System.Guid id_extra { get; set; }
        public decimal precio { get; set; }
    
        public virtual CTL_EXTRAS_PRODUCTO CTL_EXTRAS_PRODUCTO { get; set; }
        public virtual M_DETALLE_PEDIDO M_DETALLE_PEDIDO { get; set; }
    }
}
