//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viajes.DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_PEDIDO_PREGRUNTA
    {
        public System.Guid id_pregunta { get; set; }
        public System.Guid id_pedido { get; set; }
        public byte respuesta { get; set; }
    
        public virtual CTL_PREGUNTA_SERVICIO CTL_PREGUNTA_SERVICIO { get; set; }
        public virtual M_PEDIDO M_PEDIDO { get; set; }
    }
}
