//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viajes.DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_PERSONA_OPENPAY
    {
        public int id_persona { get; set; }
        public string id_customer { get; set; }
    
        public virtual CTL_PERSONA CTL_PERSONA { get; set; }
    }
}
