//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viajes.DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_BANNERS
    {
        public System.Guid id_banner { get; set; }
        public string nombre { get; set; }
        public string fotografia { get; set; }
        public int id_producto { get; set; }
        public int id_persona_alta { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public Nullable<int> id_persona_mod { get; set; }
        public string fech_mod { get; set; }
    
        public virtual CTL_PRODUCTO CTL_PRODUCTO { get; set; }
        public virtual CTL_PERSONA CTL_PERSONA { get; set; }
        public virtual CTL_PERSONA CTL_PERSONA1 { get; set; }
    }
}
