//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viajes.DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_TARIFA_ENVIO
    {
        public System.Guid id_tarifa { get; set; }
        public int distancia_menor { get; set; }
        public int distancia_mayor { get; set; }
        public decimal costo_envio { get; set; }
    }
}
