//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viajes.DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_RECHAZO_PEDIDO
    {
        public int id_persona { get; set; }
        public System.Guid id_pedido { get; set; }
        public string motivo { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual CTL_PERSONA CTL_PERSONA { get; set; }
        public virtual M_PEDIDO M_PEDIDO { get; set; }
    }
}
