//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viajes.DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_COORDENADAS_CONDUCTOR
    {
        public int id_persona { get; set; }
        public decimal latitud { get; set; }
        public decimal longitud { get; set; }
        public System.DateTime fecha { get; set; }
        public System.Guid id_coordenada { get; set; }
        public Nullable<long> id_pedido { get; set; }
    
        public virtual CTL_CONDUCTOR CTL_CONDUCTOR { get; set; }
        public virtual M_PEDIDO M_PEDIDO { get; set; }
    }
}
