//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viajes.DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_RPT_GANANCIAS
    {
        public System.Guid id_pedido { get; set; }
        public string folio { get; set; }
        public decimal costo_envio { get; set; }
        public System.DateTime fecha_pedido { get; set; }
        public string nombre_local { get; set; }
        public Nullable<decimal> costo_total { get; set; }
        public string nombre_repartidor { get; set; }
        public int total_repartidor { get; set; }
        public int total_local { get; set; }
        public int total_empresa { get; set; }
        public string tipo_pedido { get; set; }
    }
}
